export const experiences = [
	{
		duration: 'Nov 2025 - Present',
		title: 'Frontend Developer',
		company: 'Bread Cooperative',
		website: 'https://bread.coop/',
		location: 'Remote',
		employmentType: 'Open Source',
		descriptions: [
			'Promoted from open-source contributor to maintainer of all frontend repositories.',
			'Maintaining and improving React-based codebases',
		],
		techs: ['TypeScript', 'React.js', 'Next.js', 'TailwindCSS', 'Web 3' ],
	},
	{
		duration: 'May 2025 - Present',
		title: 'Senior Frontend Developer',
		company: 'Omniretail',
		website: 'https://omniretail.africa/',
		location: 'Remote, Nigeria',
		employmentType: 'Contract',
		descriptions: [
			'Led development of the core onboarding and company registration flow that powers 140K+ retailers and 65+ major FMCG brands across Africa.',
			'Provided secure authentication & authorization that handles business logic.',
			'Delivered a dashboard that provides metrics on sales and employees.',
			'Serve as a primary code reviewer (for some months), enforcing consistent code style and clean architecture, especially for newly onboarded developers.',
			'Collaborate with designers, backend teams, and cross-team frontend developers to work on different features.',
		],
		techs: ['TypeScript', 'Next.js', 'Redux', 'RTQ Query'],
	},
	{
		duration: 'Feb 2025 - Oct 2025',
		title: 'Senior Frontend Developer',
		company: 'Tasa Africa',
		website: 'https://app.tasafrica.com/signup',
		location: 'Remote, Nigeria',
		descriptions: [
			'Guided the team to better use of TypeScript.',
			'Built a GitHub Actions pipeline for previews on all project pull requests.',
			'Built a React component library for all projects.',
			'Improved main app performance',
			'Set up E2E tests during rebranding to v2',
		],
		techs: ['TypeScript', 'TailwindCSS', 'React.js', 'Vite', 'Cypress'],
	},
	{
		duration: 'April 2023 - Nov 2024',
		title: 'Lead Frontend Developer',
		company: 'HireforceOne',
		website: 'https://integration.hireforceone.com/en',
		location: 'Remote, Belgium',
		descriptions: [
			'I joined a team of 3 frontend developers to migrate a legacy React codebase to a modern Next.js architecture.',
			'4 months later, I was promoted to the team lead in which I started to lead the migration of the codebase. I also made sure best practices are put in place in terms of accessibility, testing and documentation.',
			'As it is a multilingual website, I made sure translations to other languages are seemless.',
		],
		techs: [
			'JavaScript',
			'TypeScript',
			'TailwindCSS',
			'React.js',
			'Next.js',
			'Cypress',
		],
	},
	{
		duration: 'May 2022 - May 2023',
		title: 'Software Developer',
		company: 'Projecttent',
		website: 'https://projecttent.com/',
		location: 'Remote, California',
		descriptions: [
			'I began as an intern, quickly demonstrating my abilities and earning a promotion to Software Developer within 3 months. I then built, maintained, and tested web3 applications using the Elixir stack (Elixir, Phoenix Liveview, and PostgresSQL) with Alpine.js and ClojureScript.',
			'Also, I learned the importance of effective communication within a team.',
		],
		techs: [
			'JavaScript',
			'React.js',
			'Elixir',
			'Phoenix Liveview',
			'Alphine.js',
			'Clojure',
			'ClojureScript',
			'Ecto',
			'PostgresSQL',
		],
	},
	{
		duration: 'Jan 2021 - Dec 2022',
		title: 'Frontend Developer',
		company: 'Solace Imaging',
		website: 'https://solaceimaging.com/',
		location: 'Remote, Canada',
		descriptions: [
			"I prioritized accessibility upon joining the team, ensuring all pages were usable for medical staff and patients (with disabilities). By leveraging React's capabilities, I also optimized page load times for a smooth user experience.",
		],
		techs: ['JavaScript', 'TypeScript', 'React.js'],
	},
];
