export const experiences = [
	{
		duration: "Nov 2025 - Present",
		title: "Frontend Maintainer",
		company: "Bread Cooperative",
		website: "https://bread.coop/",
		location: "Remote",
		employmentType: "Open Source",
		descriptions: [
			"Started as a contributor to crowdstaking-v2 and was promoted to maintainer of all frontend repositories.",
			"Rebuilt crowdstaking-v2 into a new version alongside the designers, and keep improving the shared UI library.",
			"Built new applications, and wrote agent instructions (CLAUDE.md and rules files) across all repos so AI coding agents follow our conventions and use the shared UI library correctly.",
			"Worked with external clients like the Ethereum Foundation, improving the frontend of the Kohaku privacy wallet extension.",
			"Act as the quality gate for incoming PRs, including AI-generated ones, using a mix of manual and AI-assisted review.",
		],
		summary:
			"Promoted from contributor to maintainer of all frontend repos. I rebuilt the flagship crowdstaking app with our designers, maintain the shared UI library, and work with clients like the Ethereum Foundation.",
		techs: ["TypeScript", "React.js", "Next.js", "TailwindCSS", "Web3"],
	},
	{
		duration: "May 2025 - Present",
		title: "Senior Frontend Engineer",
		company: "Omniretail",
		website: "https://omniretail.africa/",
		location: "Remote, Nigeria",
		employmentType: "Contract",
		descriptions: [
			"Led development of the core onboarding and company registration flow that powers 140K+ retailers and 65+ major FMCG brands across Africa.",
			"Own the single sign-on (SSO) used across all Omniretail products. I led a ground-up Next.js rewrite around React Server Components, so every page is statically prerendered and only interactive parts like forms ship JavaScript to the client. The rewrite cut client JavaScript by 26%, made Largest Contentful Paint 43% faster, brought first paint under a second, and reduced layout shift from 0.5 to almost zero.",
			// "Diagnosed deep rendering issues along the way, including a missing styled-components SSR registry, a feature-flag provider blocking first render, and a layout-shift bug in our shared UI library, then turned the fixes into a Core Web Vitals playbook and regression tests.",
			// "Eliminated our most common class of bugs, stale session data, by moving state from localStorage to the URL. Complaints dropped, and new features now ship without the bug patches that used to follow every release.",
			"Eliminated our most common class of bugs, stale session data. Complaints dropped, and new features now ship without the bug patches that used to follow every release.",
			"Built the role-based authorization layer that enforces business logic, plus a dashboard surfacing sales and employee metrics.",
			"Serve as a primary code reviewer, enforcing consistent code style and clean architecture, especially for newly onboarded developers.",
			"Collaborate with designers, backend teams, and cross-team frontend developers across multiple core projects.",
		],
		summary:
			"I led the core onboarding flow powering 140K+ retailers across Africa, and now own the SSO for all Omniretail products. My ground-up rewrite killed our most common class of bugs and brought first paint under a second.",
		techs: ["TypeScript", "Next.js", "Redux", "RTK Query"],
	},
	{
		duration: "Feb 2025 - Oct 2025",
		title: "Senior Frontend Engineer",
		company: "TasAfrica",
		website: "https://app.tasafrica.com/signup",
		location: "Remote, Nigeria",
		descriptions: [
			"Built a shared React component library adopted across all company projects.",
			"Built a GitHub Actions pipeline generating preview deployments for every pull request.",
			"Improved main app performance by removing redundant API calls and improving responsiveness and accessibility.",
			"Set up E2E test coverage (Cypress) during the rebrand to v2.",
			"Guided the team's adoption of stricter, more effective TypeScript.",
		],
		summary:
			"I built the shared React component library and the PR-preview CI pipeline used across all projects, and led TypeScript and E2E testing improvements through the v2 rebrand.",
		techs: ["TypeScript", "TailwindCSS", "React.js", "Vite", "Cypress"],
	},
	{
		duration: "April 2023 - Nov 2024",
		title: "Lead Frontend Engineer",
		company: "HireForceOne",
		website: "https://integration.hireforceone.com/en",
		location: "Remote, Belgium",
		descriptions: [
			"Joined a team of 3 frontend developers migrating a legacy React class-component codebase to Next.js, and was promoted to team lead within 4 months.",
			"Led the migration end to end while establishing best practices for accessibility, testing, and documentation.",
			"Implemented internationalization (i18n) so translations across the multilingual site stayed seamless.",
		],
		summary:
			"I led the migration from legacy React class components to Next.js after being promoted to team lead 4 months in, and set up testing, accessibility, and i18n practices along the way.",
		techs: [
			"JavaScript",
			"TypeScript",
			"TailwindCSS",
			"React.js",
			"Next.js",
			"Cypress",
		],
	},
	{
		duration: "May 2022 - May 2023",
		title: "Software Engineer",
		company: "Projecttent",
		website: "https://projecttent.com/",
		location: "Remote, California",
		descriptions: [
			"Began as an intern and was promoted to Software Engineer within 3 months.",
			"Built, maintained, and tested Web3 applications using Elixir, Phoenix LiveView, and PostgreSQL with Alpine.js and ClojureScript, a stack I learned on the job.",
			"Integrated blockchain smart contract functionality for decentralized applications.",
		],
		summary:
			"Promoted from intern to Software Engineer in 3 months. I learned Elixir, Phoenix LiveView, and ClojureScript on the job to ship decentralized applications.",
		techs: [
			"JavaScript",
			"React.js",
			"Elixir",
			"Phoenix LiveView",
			"Alpine.js",
			"ClojureScript",
			"Ecto",
			"PostgreSQL",
		],
	},
	{
		duration: "Jan 2021 - Dec 2022",
		title: "Frontend Developer",
		company: "Solace Imaging",
		website: "https://solaceimaging.com/",
		location: "Remote, Canada",
		descriptions: [
			"Prioritized accessibility (semantic HTML5 + ARIA) so every page was usable by medical staff and patients with disabilities.",
			"Optimized page load times and integrated REST APIs for dynamic experiences.",
			"Collaborated with UX/UI designers on responsive designs.",
		],
		summary:
			"Enhanced UI, integrated REST APIs, improved accessibility (semantic HTML5 + ARIA), and optimized page load times for a medical imaging product.",
		techs: ["JavaScript", "TypeScript", "React.js"],
	},
];
